### ISSUE TITLE
Better tests

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/phrg-ruby-collaborating-objects-lab#2]
Don't `expect(obj.class).to be(WhateverClass)`

Instead, `expect(obj).to be_instance_of(WhateverClass)` and get way more informative error messages.

**Comment by KFad11** [comment]
describe '#save' do
    it 'adds the artist instance to the @@all class variable' do
      expect(artist.save).to eq(artist)
      expect(Artist.all).to include(artist)
    end
  end

**Comment by garettarrowood** [comment]
Resolved in #3
